shell = "zsh -c '{}'"

[[items]]
file = "~/.config/kitty/kitty.conf"
template = "kitty"
hook = "kill -SIGUSR1 $(pgrep kitty)"

[[item]]
file= "~/.config/zathura/zathurarc"
template = "zathura"
subtemplate = "recolor"
rewrite = true

[[item]]
file = "~/.config/waybar/desktopclock/desc-colors.css"
template = "mmed"
rewrite = true

[[item]]
file = "~/.config/waybar/noback/desc-colors.css"
template = "mmed"
rewrite = true

[[item]]
file = "~/.config/hypr/hyprland.conf"
template = "hyprland"

[[item]]
file = "~/.config/nvim/lua/mmed/colors.lua"
template = "nvim"
rewrite = true

[[item]]
file = "~/.config/cava/config"
template = "cava"
rewrite = true

[[item]]
file = "~/.Xresources"
template = "Xresources"
rewrite = true
hook = "xrdb -load ~/.Xresources;wall-theme"
