shell = "zsh -c '{}'"

[[items]]
file = "~/.config/kitty/kitty.conf"
template = "kitty"
hook = "kill -SIGUSR1 $(pgrep kitty)"

[[item]]
file= "~/.config/zathura/zathurarc"
template = "zathura"
subtemplate = "recolor"
rewrite = true

[[item]]
file = "~/.config/waybar/desktopclock/desc-colors.css"
template = "akira"
rewrite = true

[[item]]
file = "~/.config/waybar/noback/desc-colors.css"
template = "akira"
rewrite = true

[[item]]
file = "~/.config/ags/desc-colors.css"
template = "akira"
rewrite = true
hook = "pkill ags;ags -c ~/.config/ags/config.js &"

[[item]]
file = "~/.config/hypr/hyprland.conf"
template = "hyprland"
hook = "sleep 1 ;toggle-monitor"

[[item]]
file = "~/.config/cava/config"
template = "cava"
rewrite = true
hook = "pkill -USR2 cava"

[[item]]
file = "~/.Xresources"
template = "Xresources"
rewrite = true
hook = "xrdb -load ~/.Xresources"

[[item]]
file = "~/.config/BetterDiscord/themes/couve.theme.css"
template = "betterdiscord"
rewrite = true
