function update {
  current_dir=$(pwd)
  cd ~/.dotfiles
  nix flake update
  sudo nixos-rebuild switch --flake . -b ~/junkyard
  home-manager switch --flake . -b .
  echo "Update complete"
  cd $current_dir
}

function reload {
  current_dir=$(pwd)
  cd ~/.dotfiles
  home-manager switch --flake . -b ~/junkyard
  echo "Reload complete"
  cd $current_dir
}

function full_reload {
  current_dir=$(pwd)
  cd ~/.dotfiles
  sudo nixos-rebuild switch --flake . -b ~/junkyard
  home-manager switch --flake . -b ~/junkyard
  echo "Reload complete"
  cd $current_dir
}

echo "
░░░    ░░░ ░░░    ░░░ ░░░░░░░ ░░░░░░  
▒▒▒▒  ▒▒▒▒ ▒▒▒▒  ▒▒▒▒ ▒▒      ▒▒   ▒▒ 
▒▒ ▒▒▒▒ ▒▒ ▒▒ ▒▒▒▒ ▒▒ ▒▒▒▒▒   ▒▒   ▒▒ 
▓▓  ▓▓  ▓▓ ▓▓  ▓▓  ▓▓ ▓▓      ▓▓   ▓▓ 
██      ██ ██      ██ ███████ ██████  
"
